# -*- coding: utf-8 -*-
TOP_PORTALS = u"\U0001F3C6 Топ-5 порталов"
ENTER_YOUR_SITE = u"\U0001F50E Найти RSS ленты"
SUBSCRIPTIONS = u"\U0001F4E8 Подписки"
RATE_BOT = u"\u2b50 Оценить бота"
CHANGE_LANGUAGE = u"\U0001F6E0 Сменить язык"
DONATE = u"\U0001F4B5 Donate"
FEEDBACK = u"\u270d Отзыв"
VK = u"\U0001F465 vk.com"
GREETING = u"Привет, %s! \u270b \nСделайте свой выбор:"
MAKE_YOUR_CHOICE = "Сделайте свой выбор:"
RUSSIA = u"\U0001F1F7\U0001F1FA Россия"
BELARUS = u"\U0001F1E7\U0001F1FE Беларусь"
UKRAINE = u"\U0001F1FA\U0001F1E6 Украина"
WORLD = u"\U0001F30E Мир"
BACK_TO_MAIN_MENU = u"\U0001F519 В главное меню"
CHOOSE_THE_COUNTRY = "Выберите страну:"
TOP_PUBLICS = u"\U0001F3C6 Топ-5 пабликов"
FIND_PUBLIC = u"\U0001F50E Найти паблик"
ENTER_FEEDBACK = "Пожалуйста, напишите свой отзыв ниже, или отправьте e-mail: feedlerbot@gmail.com"
THANKS_FOR_FEEDBACK = "Спасибо за отзыв!"
ENTER_ANOTHER_SITE = u"\U0001F50E Ввести другой сайт"
ENTER_SITE_OR_RSS = "Введите адрес сайта или RSS ленты:"
REQUESTED_SITE_PRESENTS = "Запрашиваемый сайт есть в разделе «Топ-5 порталов»"
SELECT_SITE = "Выберите сайт:"
BACK_TO_COUNTRIES = u"\U0001F519 Назад к выбору страны"
BACK_TO_SELECTION = u"\U0001F519 Назад к выбору"
SEARCHING = "Идет поиск..."
SELECT_RSS_CHANNEL = u"\u2139 Было найдено %s RSS лент:"
SUBSCRIBE = u"\U0001F4E8 Подписаться"
UNSUBSCRIBE = u"\u274C Отписаться"
READ = u"\U0001F4F0 Читать"
RSS_FEEDS_NOT_FOUND = "RSS лент не найдено, введите другой сайт"
SELECT_PUBLIC = "Выберите паблик:"
BACK_TO_SITE_SELECTION = u"\U0001F519 Назад к выбору сайта"
CHOOSE_SECTION = "Выберите раздел %s:"
YOU_CAN_SUBSCRIBE_TO = u"\U0001F4A1 Вы можете подписаться на %s, используя меню ниже"
YOU_CAN_UNSUBSCRIBE_FROM = u"\U0001F4A1 Вы можете отписаться от %s, используя меню ниже"
SUBSCRIBE_TO = u"\U0001F4E8 Подписаться на %s"
UNSUBSCRIBE_FROM = u"\u274C Отписаться от %s"
LATEST_NEWS = "Последние новости %s из раздела *«%s»*:"
CHOOSE_ANOTHER_SECTION = u"\U0001F4DC Выбрать другой раздел"
ALL_LASTEST_NEWS_DISPLAYED = "Все последние новости из раздела *«%s»* выведены. Можете выбрать другой раздел:"
READ_MORE = u"\U0001F4F0 Read More"
RECENT_PUBLIC_POSTS = "Последние записи из паблика *«%s»*:"
ALL_LASTEST_POSTS_DISPLAYED = "Все последние записи из паблика выведены. Можете выбрать другой."
SELECT_ANOTHER_PUBLIC = u"\U0001F465 Выбрать другой паблик"
SELECT_LANGUAGE = "Выберите язык"
CHANGED_LANGUAGE = "Язык был успешно изменён!"
WELCOME_BACK = "С возвращением, %s!"
SUCCESSFULLY_SUBSCRIBED = "Вы успешно подписаны на %s!\nБот будет присылать вам свежие новости каждый час."
SUCCESSFULLY_UNSUBSCRIBED = "Вы были успешно отписаны от %s!"
LIST_OF_SUBSCRIPTIONS = "Список ваших подписок:"
YOU_HAVE_NO_SUBSCRIPTIONS = "У вас нет подписок"
ALREADY_SUBSCRIBED_TO = "Вы уже подписаны на %s"
YOU_CAN_SUBSCRIBE = u"\U0001F4A1 Вы можете подписаться на найденные RSS ленты, используя меню ниже"
YOU_CAN_UNSUBSCRIBE = u"\U0001F4A1 Вы можете отписаться от RSS лент, используя меню ниже"
REQUESTED_SITE_RETURN_ERROR = "Запрашиваемый сайт вернул ошибку: *«%s»*"
HERE_IS_LATEST_NEWS = u"\U0001F4EC Последние новости из ленты %s:"
ALL_FEEDS_UPDATED = u"\u2139 Все подписки обновлены \u2139"
IF_YOUR_LIKE = u"Если вам действительно нравится этот бот, то будем рады любому " \
               u"пожертвованию которое уйдет на разработку, обслуживание и серверы. \n" \
               u"Вы можете отправить пожертвование напрямую на кошелёк *WebMoney: Z638231318037*, " \
               u"либо перейти по ссылке ниже"
RATE_ME = u"Если вам нравится этот бот, то поставьте ему \u2b50\u2b50\u2b50\u2b50\u2b50 здесь:"
ALREADY_SUPPORTED = u"\u2705 Я уже поддержал бота"
GOT_IT = u"Принято! Вы лучший! \U0001F44D"
REMINDER = u"Нравится наш бот? — Поставьте ему \u2b50\u2b50\u2b50\u2b50\u2b50"
SUPPORT_GROUP = u"\u2139 Вступайте в нашу группу поддержки. \nТам Вы можете задать интересующие Вас вопросы по " \
                u"работе бота и узнать первыми о новых функциях. " \
                u"Также, будем рады любым замечаниям и предложениям.\n"
HELP = u"\U0001F511 Помощь"
LIST_OF_COMMANDS = "*Вместо главного меню, Вы можете использовать следующие команды:* \n" \
                   "/search - Ищите RSS/Atom-ленты и подписывайтесь на них. " \
                   "Также, бот может найти ленты на YouTube каналах и LiveJournal блогах\n" \
                   "/subscriptions - Список ваших подписок\n" \
                   "/top5 - Читайте новости по топовым новостным ресурсам " \
                   "в режиме реального времени\n" \
                   "/vk - Просматривайте мемы в топовых VK группах в режиме реального времени\n" \
                   "/feedback - Мы будем рады любому отзыву\n" \
                   "/language - Изменить язык"
SUPPORT_TEAM_LINK = "https://t.me/joinchat/GO9Jew3ZH_-yj3yUyd5biA"
SUPPORT_TEAM = u"\U0001F6E0 Служба поддержки"
